application: try-hy
version: 1
runtime: python27
api_version: 1
threadsafe: yes
automatic_scaling:
  min_idle_instances: 1

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: .*
  script: main.__hymain__.app
