name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: build-sphinx
        uses: sphinx-notes/pages@v3
        with:
          publish: "false"
      - name: Upload artifact
        run: mkdir ${{ steps.build-sphinx.outputs.artifact }}/stable && cp -r ${{ steps.build-sphinx.outputs.artifact }}/* ${{ steps.build-sphinx.outputs.artifact }}/stable
